CREATE SEQUENCE seq_shop_user NOCYCLE NOCACHE;
CREATE SEQUENCE seq_shop_protype NOCYCLE NOCACHE;
CREATE SEQUENCE seq_shop_product NOCYCLE NOCACHE;
CREATE SEQUENCE seq_shop_pro_image NOCYCLE NOCACHE;
CREATE SEQUENCE seq_shop_pro_review NOCYCLE NOCACHE;
CREATE SEQUENCE seq_shop_orderitem NOCYCLE NOCACHE;
CREATE SEQUENCE seq_shop_order NOCYCLE NOCACHE;

